# Generated by Django 4.2.4 on 2023-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='material',
            field=models.CharField(choices=[('Debit card', 'Debit card'), ('Credit card', 'Credit card'), ('Cheque book', 'Cheque book')], max_length=100),
        ),
    ]
